const $=s=>document.querySelector(s), canvas=$('#canvas'),ctx=canvas.getContext('2d');
let socket,state,img,pieces=[],selected=null,grid=5,preview='',room='',cell=60,margin=18,boardX=0,boardY=0,lastSent=0;
const fallback='https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85';
function toast(t){const e=$('#status');e.textContent=t;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),2400)}
function modal(type){$('#modal').hidden=false;$('#createForm').hidden=type!=='create';$('#joinForm').hidden=type!=='join';if(type==='join')setTimeout(()=>$('#code').focus(),50)}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>modal(b.dataset.open));$('#close').onclick=()=>$('#modal').hidden=true;document.querySelector('[data-scroll]').onclick=()=>$('#steps').scrollIntoView({behavior:'smooth'});
document.querySelectorAll('.level').forEach(b=>b.onclick=()=>{document.querySelectorAll('.level').forEach(x=>x.classList.remove('active'));b.classList.add('active');grid=+b.dataset.grid});
$('#photo').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>8e6)return toast('En fazla 8 MB JPG, PNG veya WebP seçin.');const b=await createImageBitmap(f),side=Math.min(b.width,b.height),c=document.createElement('canvas');c.width=c.height=1000;c.getContext('2d').drawImage(b,(b.width-side)/2,(b.height-side)/2,side,side,0,0,1000,1000);preview=c.toDataURL('image/jpeg',.82);$('#photoText').textContent=f.name;};
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}
function connect(roomCode,onopen){room=roomCode.toLowerCase();socket?.close();socket=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host);socket.onopen=()=>{socket.send(JSON.stringify({type:'join',room,name:'Oyuncu'}));onopen?.()};socket.onmessage=async e=>{const m=JSON.parse(e.data);if(m.type==='error')return toast(m.message);if(m.type==='state'){if(!m.state)return;state=m.state;await load(state.image);openGame()}if(m.type==='move'){const p=pieces.find(x=>x.id===m.id);if(p){Object.assign(p,m.pos);draw()}}if(m.type==='lock'){const p=pieces.find(x=>x.id===m.id);if(p){p.locked=true;draw()}}if(m.type==='unlock'){const p=pieces.find(x=>x.id===m.id);if(p){p.locked=false;draw()}}if(m.type==='presence'){$('#players').innerHTML='● Sen<br><span style="color:#d66f62">● Bir oyuncu '+(m.joined?'katıldı':'ayrıldı')+'</span>'}};socket.onclose=()=>state&&toast('Bağlantı kesildi.');}
$('#create').onclick=()=>{const c=code();connect(c,()=>socket.send(JSON.stringify({type:'create',room,grid,image:preview||fallback,seed:crypto.getRandomValues(new Uint32Array(1))[0],finish:$('#finish').value})));$('#create').disabled=true;$('#create').textContent='Hazırlanıyor…'};
$('#join').onclick=()=>{const c=$('#code').value.trim();if(!/^[a-z0-9]{6}$/i.test(c))return toast('Altı karakterli oda kodunu yazın.');connect(c,()=>{});setTimeout(()=>{if(!state)toast('Oda bulunamadı veya henüz hazır değil.')},1800)};
function openGame(){$('#modal').hidden=true;$('#home').hidden=true;$('#game').hidden=false;$('#roomLabel').textContent='Oda: '+room.toUpperCase();$('#create').disabled=false;$('#create').textContent='Masayı hazırla →';history.replaceState(null,'','#'+room.toUpperCase());draw()}
$('#leave').onclick=()=>location.href=location.pathname;$('#share').onclick=async()=>{const text='Birlikte puzzle yapalım! Oda kodu: '+room.toUpperCase()+' '+location.origin;try{await navigator.clipboard.writeText(text);toast('Davet metni kopyalandı.')}catch{toast(text)}};
function rand(seed){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function edges(g,seed){const r=rand(seed||1),h=[],v=[];for(let y=0;y<g-1;y++)for(let x=0;x<g;x++)h.push(r()<.5?-1:1);for(let y=0;y<g;y++)for(let x=0;x<g-1;x++)v.push(r()<.5?-1:1);return{h,v}}
function outline(top,right,bottom,left){const p=new Path2D();p.moveTo(0,0);function edge(ax,ay,bx,by,s){const dx=bx-ax,dy=by-ay,len=Math.hypot(dx,dy),nx=dy/len,ny=-dx/len,pt=(u,w=0)=>[ax+dx*u+nx*w*len*s,ay+dy*u+ny*w*len*s],line=(u,w=0)=>p.lineTo(...pt(u,w)),curve=(a,b,c)=>p.bezierCurveTo(...pt(...a),...pt(...b),...pt(...c));if(!s)return line(1);line(.29);curve([.35,0],[.39,-.045],[.38,-.085]);curve([.34,-.16],[.41,-.235],[.5,-.235]);curve([.59,-.235],[.66,-.16],[.62,-.085]);curve([.61,-.045],[.65,0],[.71,0]);line(1)}edge(0,0,cell,0,top);edge(cell,0,cell,cell,right);edge(cell,cell,0,cell,bottom);edge(0,cell,0,0,left);p.closePath();return p}
function layout(){const g=state.grid,available=Math.max(720,innerWidth<800?g*46*2+100:900);cell=Math.max(42,Math.min(67,Math.floor((available-110)/(g*2))));margin=Math.ceil(cell*.3);boardX=g*cell+margin*5;boardY=margin*2;canvas.width=boardX+g*cell+margin*3;canvas.height=Math.max(g*cell+margin*4,530)}
function build(){layout();const g=state.grid,e=edges(g,state.seed),r=rand(state.seed^99131);pieces=[];for(let y=0;y<g;y++)for(let x=0;x<g;x++){const id=y*g+x,pos=state.positions[id]||{x:margin+r()*(g*cell-cell),y:margin+r()*(g*cell-cell)};pieces.push({id,row:y,col:x,x:pos.x,y:pos.y,done:!!pos.done,locked:false,shape:outline(y?-e.h[(y-1)*g+x]:0,x<g-1?e.v[y*(g-1)+x]:0,y<g-1?e.h[y*g+x]:0,x?-e.v[y*(g-1)+x-1]:0)})}draw()}
async function load(src){const im=new Image();im.crossOrigin='anonymous';im.src=src;await im.decode();img=im;build()}
function draw(){if(!state||!img)return;ctx.clearRect(0,0,canvas.width,canvas.height);const g=state.grid;ctx.fillStyle='#e8e1d5';ctx.fillRect(boardX,boardY,g*cell,g*cell);ctx.save();ctx.globalAlpha=.22;ctx.drawImage(img,boardX,boardY,g*cell,g*cell);ctx.restore();ctx.strokeStyle='#bcb4a8';ctx.lineWidth=2;ctx.strokeRect(boardX,boardY,g*cell,g*cell);for(const p of pieces){ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor='#0006';ctx.shadowBlur=p.done?0:7;ctx.shadowOffsetY=3;ctx.fillStyle='#fff';ctx.fill(p.shape);ctx.shadowColor='transparent';ctx.save();ctx.clip(p.shape);ctx.drawImage(img,-p.col*cell,-p.row*cell,g*cell,g*cell);ctx.restore();ctx.strokeStyle=p===selected?'#ffd16d':p.locked?'#e26c60':'#fff';ctx.lineWidth=p===selected?4:1.5;ctx.stroke(p.shape);ctx.restore()}const n=pieces.filter(p=>p.done).length,total=pieces.length,pc=total?Math.round(n/total*100):0;$('#count').textContent=n+' / '+total+' parça';$('#percent').textContent='%'+pc;$('#bar').style.width=pc+'%';if(total&&n===total)toast(state.finish||'Birlikte tamamladınız!')}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.onpointerdown=e=>{const q=point(e);for(let i=pieces.length-1;i>=0;i--){const p=pieces[i];if(p.done||p.locked||!ctx.isPointInPath(p.shape,q.x-p.x,q.y-p.y))continue;selected=p;p.off={x:q.x-p.x,y:q.y-p.y};pieces.splice(i,1);pieces.push(p);canvas.setPointerCapture(e.pointerId);socket.send(JSON.stringify({type:'lock',room,id:p.id}));draw();break}}
canvas.onpointermove=e=>{if(!selected)return;const q=point(e);selected.x=q.x-selected.off.x;selected.y=q.y-selected.off.y;draw();if(Date.now()-lastSent>70){socket.send(JSON.stringify({type:'move',room,id:selected.id,pos:{x:selected.x,y:selected.y,done:false}}));lastSent=Date.now()}}
function drop(){if(!selected)return;const p=selected,tx=boardX+p.col*cell,ty=boardY+p.row*cell;if(Math.hypot(p.x-tx,p.y-ty)<cell*.34){p.x=tx;p.y=ty;p.done=true}socket.send(JSON.stringify({type:'move',room,id:p.id,pos:{x:p.x,y:p.y,done:p.done}}));if(!p.done)socket.send(JSON.stringify({type:'unlock',room,id:p.id}));selected=null;draw()}
canvas.onpointerup=drop;canvas.onpointercancel=drop;addEventListener('resize',()=>state&&!selected&&build());const hash=location.hash.slice(1);if(/^[a-z0-9]{6}$/i.test(hash)){modal('join');$('#code').value=hash}
